config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :auths
  resources :categories, only: [:show, :index] do
    resources :items
    resources :votes, only: [:create]
  end
end

app/models/auth.rb
class Auth < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user

  after_create :create_and_link_user

  protected
    def create_and_link_user
      user = User.create({ auth_id: self.id })
      self.update({ user_id: user.id })
    end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  has_many :items

  def item_ranks
    return self.items.select(:rank).distinct
  end

  def item_rank_chartdata
    normalize_to = self.items.minimum(:rank) - 1
    data = []
    self.items.select(:name, :rank).each do |item|
      data.push([item.name, item.rank - normalize_to])
    end
    return data
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :category
  acts_as_votable
  default_scope { order('rank DESC') }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :auth
  acts_as_voter

  def has_voted_today_for(category)
    self.votes.each do |vote|
      vote_date = vote.created_at
      vote_category = Item.find(vote.votable_id).category
      if vote_date.today? && (vote_category.id == category.id)
        return true
      end
    end
    return false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    render 'static_page/index'
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @item = @category.items.new
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_category, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @category.items
  end

  def show
  end

  def new
    @item = @category.items.new
  end

  def create
    @item = @category.items.new(item_params)

    if @item.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def destroy
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ActionController::Base

  def create
    item_up = Item.find(params[:voted_up_item_id])
    item_down = Item.find(params[:voted_down_item_id])

    item_up.vote_by :voter => current_auth.user, :duplicate => true
    item_up.increment!(:rank)

    item_down.vote_by :voter => current_auth.user, :vote => 'bad', :duplicate => true
    item_down.decrement!(:rank)

    redirect_to category_path(params[:category_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_pie_chart.erb
<%= pie_chart @category.item_rank_chartdata, library: {legend: {position: "top", maxLines: 10}} %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<div>

  <ul>
    <% @categories.each do |category| %>

    <li>
      <%= link_to category.name, category_path(category) %>
    </li>
    <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<div class="container-fluid">
  <div class="row">
    <h1 class="bangtext" style="text-align: center;">Best: <%= @category.name %></h1>
    <hr>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="item-list" id="item-list-better">
        <% rank_counter = 0 %>
        <% @category.item_ranks.each do |rank| %>
          <% rank_counter += 1 %>
            <div class="rank-group" data-rank="<%= rank_counter %>">
              <div class="rank-text">Ranked #<%= rank_counter %></div>
              <% @category.items.where(rank: rank.rank).each do |item| %>
              <div class="rank-item rank-left" data-id="<%= item.id %>">
                <%= item.name %>
              </div>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-4 center-panel">

      <% if auth_signed_in? == false %>
        <h4>Sign up or log in to vote!</h4>
        <br><br>
        <%= render 'pie_chart' %>
      <% else %>

        <% if current_auth.user.has_voted_today_for(@category) %>

          <div id="already-voted">
            <h2 style="text-align: center">Thanks for voting!</h2>
            <h4 style="text-align: center">Be sure to come back tomorrow for another chance to vote!</h4>
            <br><br>
            <%= render 'pie_chart' %>
          </div>

        <% else %>

          <div class="center-col" id="left-thing">
            <h3>
              <span class="glyphicon glyphicon-hand-left"></span>
              Which one deserves more props?
            </h3>
            <div class="centered">
              <br>
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-item-modal">
                Wait - I have one that's better than ALL of these!
              </button>
              <span style='font-style: italic;'>(add another <%= @category.name %>)</span>
            </div>
          </div>

          <div class="center-col start-hidden" id="better-than">
            <h2 style="text-align: center;">IS BETTER THAN:</h2>
          </div>

          <div class="center-col start-hidden" id="right-thing">
            <h3 style="text-align: right;">
              Which one is overrated?
              <span class="glyphicon glyphicon-hand-right"></span>
            </h3>
          </div>

          <div class="center-col start-hidden" id="vote-thing">
            <h4 style="text-align: center;">CAN YOU DIG IT??</h4>
            <div class="btn btn-lg btn-block btn-primary" id="vote-button">Cast this vote!</div>
            <br>
          </div>

        <% end %>

      <% end %>

    </div>

    <div class="col-md-4">
      <div class="item-list" id="item-list-worse">
        <% rank_counter = 0 %>
        <% @category.item_ranks.each do |rank| %>
        <% rank_counter += 1 %>
        <div class="rank-group" data-rank="<%= rank_counter %>">
          <div class="rank-text">Ranked #<%= rank_counter %></div>
          <% @category.items.where(rank: rank.rank).each do |item| %>
          <div class="rank-item rank-right" data-id="<%= item.id %>">
            <%= item.name %>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>

  </div>

  <div class="row start-hidden">
    <%= form_tag(category_votes_path([@category]), action: :create, method: :post, id: 'vote-form') do %>
    voted_up_item_id<%= text_field_tag :voted_up_item_id %>
    voted_down_item_id<%= text_field_tag :voted_down_item_id %>
    <%= submit_tag "Vote!" %>
    <% end %>
  </div>

  <div class="modal fade" id="add-item-modal" tabindex="-1" role="dialog" aria-labelledby="addItem">
    <div class="modal-dialog modal-sm">
      <div class="modal-content modal-padding">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">New Item</h4>
        </div>
        <%= render '/items/form' %>
      </div>
    </div>
  </div>
</div>

<div class="underlay">
  <img src="<%= @category.image_url %>" alt="" />
</div>

app/views/items/_form.html.erb
<%= render('layouts/errors', :object => @item) %>

<%= form_for [@category, @item] do |f| %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
</div>

<%= f.submit 'Add', class: "btn btn-primary btn-block" %>
<% end %>

app/views/items/new.html.erb
<h1>New Item:</h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BetterThan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container">

    <nav class="navbar navbar-default navbar-inverse">

      <div class="row">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <a class="navbar-brand bangtext logo" href="/">BetterThan</a>
          </div>
          <div class="navbar">
            <ul class="nav navbar-nav navbar-right">
              <% if auth_signed_in? && current_auth.user.admin %>
              <li><%= link_to 'Admin Panel', rails_admin_path %></li>
              <% end %>
              <% if auth_signed_in? %>
              <li><span style="color: white;">Hello, <%= current_auth.email %></span></li>
              <li><%= link_to "Log Out", destroy_auth_session_path, :method => :delete %></li>
              <% else %>
              <li><%= link_to "Log In", new_auth_session_path %></li>
              <li><%= link_to "Sign Up", new_auth_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div><!-- /.container-fluid -->
      </div>
      <div class="row">
        <div class="container-fluid">
          <div class="navbar-header">
            <ul class="nav navbar-nav">
              <% Category.all.each do |category| %>
                <li><%= link_to category.name, category_path(category) %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

    </nav>


    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </div>

</body>
</html>

app/views/static_page/index.html.erb
<div class="landing-text">
  <h2>What is BetterThan?</h2>
  <p>
    BetterThan Solves the question "which is better" by combining two great systems: <strong>DEMOCRACY</strong> and <strong>WASTING TIME ON THE INTERNET!</strong>
  </p>
  <h3>How does it work??</h3>
  <p>
    Just sign up for an account (<span class="glyphicon glyphicon-hand-up"></span>
    <span class="glyphicon glyphicon-hand-up"></span><span class="glyphicon glyphicon-hand-up"></span> up there!!)
     and click any one of the many available categories (<span class="glyphicon glyphicon-hand-up"></span>
    <span class="glyphicon glyphicon-hand-up"></span><span class="glyphicon glyphicon-hand-up"></span> also up there!!!)
     - check out the current rankings and look for a <strong>GROSS MISCARRIAGE OF JUSTICE</strong>
      that needs to be corrected - you can choose one option and vote it up to its rightful place, plus one other that need to be brought back down into the mud where it belongs.
  </p>
  <h3>But wait! I voted and the rankings are still totally whack, y'all!!</h3>
  <p>
    <strong>DON'T WORRY!</strong> you can come back once every day and vote against until the rankings reflect the strong <strong>ULTIMATE TRUTH.</strong>
    But be warned! Other people with less taste and intelligence will also be voting - the only option for you is to <strong>STAY DILLIGENT</strong> and come back
    <strong>EVERY DAY</strong> to prove you care about truth, justice, and accurate rankings of culture, media, and life itself!
  </p>
</div>